### ISSUE TITLE
Decide on a name

### ISSUE THREAD

**Issue by cz** [assemblehere/assemble-design#3]
Some names I've used as placeholders so far:

- Cadre
- Troop

**Comment by johnhenrymuller** [comment]
Other name ideas our discussion:
- Mobilize
- Assemble
_(these names are believed to sound “less-militant” — working within democracy)_

**Comment by cz** [comment]
Couple more metaphorical concepts that have crossed my mind, just to keep the juices flowing:

- Swell (Groundswell, Wave, grow larger, etc)
- Snowball (e.g snowball effect, "let's roll", etc—and a play on the "snowflakes" insult)
- Unrest (prob too negative/militant but I thought the contrast with rest/inaction was fun)

**Comment by nick-adams** [comment]
Oh, I kind of like the owning of the snowflake thing...

Blizzard. Squall. Storm. etc

Thats right we're snowflakes, motherfucking winter is coming.

**Comment by cz** [comment]
Going with Assemble
